#!/bin/sh
set -x

set -x
INITDIR=$(cd $(dirname $0); pwd)

# Don't use symlink for .emacs, we want to be able to use native Emacs
# on Windows. In general, the mechanism for determining HOME and
# resolving ~ in paths is very different on Windows and Linux. See the Emacs
# manual for further info.
DOTEMACS=$HOME/.emacs
case `uname -s` in
    CYGWIN*)
	INITDIR_NATIVE=$(cygpath -m "$INITDIR")
	HOME_NATIVE=$(cygpath -m "$HOME")
	cat >$DOTEMACS <<EOF
;; This file is automatically generated by $INITDIR/$(basename $0)
(setenv "HOME" "$INITDIR_NATIVE")
(load-file "$INITDIR_NATIVE/.emacs")
(cd "$HOME_NATIVE")
EOF
	;;
    *)
	INITDIR_NATIVE=$INITDIR
	HOME_NATIVE=$HOME

	rm -f $HOME/.emacs
	ln -s $INITDIR/.emacs $HOME/.emacs

	rm -f $HOME/elisp
	ln -s $INITDIR/elisp $HOME/elisp

	rm -f $HOME/emacs-modules
	ln -s $INITDIR/emacs-modules $HOME/emacs-modules
	
	;;
esac

rm -f $HOME/.bashrc
ln -s $INITDIR/.bashrc_user $HOME/.bashrc

rm -f $HOME/.bash_functions
ln -s $INITDIR/.bash_functions $HOME/.bash_functions

rm -f $HOME/.bash_aliases
ln -s $INITDIR/.bash_aliases $HOME/.bash_aliases

rm -f $HOME/.bash_profile
ln -s $INITDIR/.bash_profile $HOME/.bash_profile

rm -f $HOME/.inputrc
ln -s $INITDIR/.inputrc $HOME/.inputrc

rm -f $HOME/.screenrc
ln -s $INITDIR/.screenrc $HOME/.screenrc

rm -f $HOME/.gnus
ln -s $INITDIR/.gnus $HOME/.gnus

rm -f $HOME/.gitconfig
ln -s $INITDIR/.gitconfig $HOME/.gitconfig

# svn co http://svn.iar.se/tools/emacs-modules/trunk $INITDIR_NATIVE/emacs-modules
